# Generated by Django 4.0.1 on 2022-02-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='max_goods_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='wheel_count',
            field=models.IntegerField(),
        ),
    ]
